# Generated by Django 4.2.5 on 2023-09-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postmodel_image_postmodel_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='file',
            field=models.FileField(null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
