# Generated by Django 4.2.5 on 2023-09-22 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orders', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.ordersmodel')),
                ('produc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.productmodel')),
            ],
        ),
    ]
