# Generated by Django 4.2.5 on 2023-09-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho', models.CharField(max_length=20)),
                ('ten', models.CharField(max_length=255)),
                ('ngay_sinh', models.DateField()),
                ('dia_chi', models.TextField()),
                ('diem_toan', models.IntegerField()),
                ('diem_van', models.IntegerField()),
                ('diem_anh', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
